// Isolated browser smoke test. All network traffic is mocked; no live API or guest data.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const root=path.resolve(import.meta.dirname,'..');
const runtime=path.join(root,'tests/.runtime');
const require=createRequire(path.join(runtime,'package.json'));
const ignore=require('ignore')().add(fs.readFileSync(path.join(root,'.gitignore'),'utf8'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const profile=fs.mkdtempSync(path.join(runtime,'browser-features-'));
const browser=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:390,height:844},serviceWorkers:'block'});
const origin='https://tour.example.invalid';
const stored=new Map(),errors=[];
let role=null, apiUnavailable=false, loginRequests=0;
try {
  await browser.route('**/*',async route=>{
    const url=new URL(route.request().url());
    if(url.origin!==origin)return route.abort();
    if(url.pathname.endsWith('/api.php')) {
      const body=route.request().postDataJSON() || {},action=body.action || url.searchParams.get('action');
      let data={ok:true};
      if(apiUnavailable)return route.fulfill({status:503,json:{error:'Synthetic unavailable'}});
      if(action==='login') {
        loginRequests++;
        if(body.role!=='admin' || body.password!=='synthetic-browser-password')return route.fulfill({status:401,json:{error:'Sign-in failed.'}});
        role='admin';
      }
      if(action==='lockAdmin')role=null;
      if(['session','login','lockAdmin'].includes(action))data={role,csrfToken:'synthetic-csrf',config:{analyticsEnabled:true,uploadsEnabled:false}};
      if(action==='list')data={keys:[...stored.keys()].filter(k=>k.startsWith(url.searchParams.get('prefix')||''))};
      if(action==='get')data={value:stored.get(url.searchParams.get('key'))||null};
      if(action==='resourcePreview')data={preview:{title:'Synthetic preview title',description:'Synthetic page description',image:origin+'/WWHI22L26A/assets/shared/experiences/versailles-palace-and-gardens.jpg',publisher:'Example'}};
      if(action==='set')stored.set(body.key,body.value);
      if(action==='analyticsSummary')data={enabled:true,events:[],onward:{total:1,flying:0,eurostar:1,staying:0}};
      return route.fulfill({json:data});
    }
    const rel=decodeURIComponent(url.pathname.replace('/WWHI22L26A/','')) || 'index.html';
    if(rel.includes('..') || rel.startsWith('.') || ignore.ignores(rel) || !/\.(html|js|css|json|png|jpe?g|ico)$/.test(rel))return route.abort();
    const file=path.join(root,rel);if(!fs.existsSync(file))return route.abort();
    const types={html:'text/html',js:'text/javascript',css:'text/css',json:'application/json',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',ico:'image/x-icon'};
    return route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file).slice(1)]});
  });
  const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin+'/WWHI22L26A/');
  await page.getByRole('button',{name:'Complete Form',exact:true}).first().waitFor();
  assert.equal(loginRequests,0,'Root URL opens without any login');
  assert.equal(await page.locator('input[type=password]').count(),0,'No guest password prompt');
  assert.equal(await page.evaluate(()=>ADMIN_MODE),false,'Anonymous startup has no admin privileges');
  await page.evaluate(()=>setTab('tools'));
  assert.equal(await page.locator('[data-tool-id=photos]').count(),0,'Private guest photos are not public tools');
  await page.getByRole('button',{name:'Unlock Admin',exact:true}).click();
  await page.locator('[data-admin-pin]').fill('incorrect-synthetic-password');
  await page.getByRole('button',{name:'Unlock',exact:true}).click();
  await page.getByText('Sign-in failed.',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>ADMIN_MODE),false,'Wrong password cannot enable admin');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.evaluate(()=>setTab('today'));
  await page.getByRole('button',{name:'Complete Form',exact:true}).first().click();
  await page.locator('#onward-name').fill('Synthetic browser traveller');
  await page.locator('input[name=onward-plan][value=eurostar]').check();
  assert.equal(await page.locator("#onward-eurostar-time, #onward-eurostar-ref, #onward-london-airport, #onward-london-airline").count(),0);
  await page.locator("#onward-london-flight-date").fill("2026-10-23");
  await page.locator("#onward-london-flight-time").fill("13:00");
  await page.locator("#onward-london-terminal").fill("5");
  await page.locator("#onward-london-flight-number").fill("EX456");
  await page.locator('#onward-submit').click();
  await page.getByText('Thank you. Your onward travel details have been submitted.',{exact:true}).waitFor();
  assert.equal(stored.size,1);
  const saved=JSON.parse([...stored.values()][0]);assert.equal(saved.plan,'eurostar');assert.ok(!saved.londonAirport);
  await page.evaluate(()=>{setOnwardTravelOpen(false);setTab('tools');});
  await page.getByRole('button',{name:'Unlock Admin',exact:true}).click();
  await page.locator('[data-admin-pin]').fill('synthetic-browser-password');
  await page.getByRole('button',{name:'Unlock',exact:true}).click();
  await page.waitForFunction(()=>ADMIN_MODE);
  await page.evaluate(()=>{quickAdminOpen=false;FULL_ADMIN_UI=true;setAdminDay(5);setTab('today');});
  const editor=page.locator('#scr-today .day-resource-editor');await editor.locator('summary').click();
  await editor.locator('[name=url]').fill('https://example.invalid/guide');await editor.locator('[name=title]').fill('Synthetic city guide');
  await editor.getByRole('button',{name:'Save resource'}).click();
  await page.locator('#scr-today .day-link-title').filter({hasText:'Synthetic city guide'}).waitFor();
  assert.ok([...stored.values()].some(value=>value.includes('Synthetic page description') && value.includes('versailles-palace-and-gardens.jpg')),'Link preview image is saved for all guests');
  assert.equal(await page.locator('#scr-today .day-link-image').count(),1,'Saved link displays its preview image');
  await page.evaluate(()=>{setTab('programme');toggleItineraryDay(5);});
  await page.locator('#scr-programme .i-day.open .day-link-title').filter({hasText:'Synthetic city guide'}).waitFor();
  await page.evaluate(()=>setTab('today'));await page.locator('#scr-today .journey-recap-card summary').click();
  await page.locator('#scr-today .journey-recap-card').screenshot({path:path.join(runtime,'recap-mobile.png')});
  await page.setViewportSize({width:1280,height:900});
  await page.locator('#scr-today .day-links-section').screenshot({path:path.join(runtime,'resources-desktop.png')});
  await page.evaluate(()=>{setTab('tools');openToolPanel('analytics');});
  await page.getByRole('button',{name:'Refresh analytics',exact:true}).waitFor();
  await page.waitForFunction(()=>remoteAnalyticsCache!==null);
  assert.equal(await page.locator('[data-onward-completed]').innerText(),'1','Analytics displays saved-form count');
  await page.getByRole('button',{name:'Generate onward travel Excel',exact:true}).click();
  await page.getByRole('button',{name:'Download Excel Sheet',exact:true}).waitFor();
  const downloading=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download Excel Sheet',exact:true}).click();
  const download=await downloading;
  assert.equal(download.suggestedFilename(),'WWHI22L26A-guest-flight-details.xlsx');
  await download.saveAs(path.join(runtime,'browser-onward.xlsx'));
  await page.evaluate(()=>setTab('experiences'));
  const versailles=page.locator('#scr-experiences .exp-img-wrap--versailles');
  await versailles.waitFor();
  for (const width of [390,1280]) {
    await page.setViewportSize({width,height:900});
    await versailles.screenshot({path:path.join(runtime,`versailles-${width}.png`)});
    const box=await versailles.boundingBox();
    assert.ok(Math.abs(box.width / box.height - 850 / 380)<0.05,'Versailles frames the photograph without the grey banner');
  }
  await page.emulateMedia({colorScheme:'dark'});
  await page.goto(origin+"/WWHI22L26A/?admin=1");
  await page.getByRole("dialog",{name:"Admin unlock",exact:true}).waitFor();
  assert.equal(role,null,"Explicit admin URL revokes the old admin session");
  assert.equal(await page.evaluate(()=>ADMIN_MODE),false);
  await page.locator("[data-admin-pin]").fill("synthetic-browser-password");
  await page.getByRole("button",{name:"Unlock",exact:true}).click();
  await page.getByRole("dialog",{name:"Quick edit today",exact:true}).waitFor();
  assert.equal(await page.locator('.quick-admin-overlay').evaluate(el=>getComputedStyle(el).backdropFilter),'none');
  assert.equal(await page.locator('.quick-admin-panel').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
  assert.equal(await page.locator('[data-quick-time]').first().evaluate(el=>getComputedStyle(el).color),'rgb(22, 22, 22)');
  await page.getByRole('dialog',{name:'Quick edit today',exact:true}).screenshot({path:path.join(runtime,'admin-editor-dark-system.png')});
  assert.ok(await page.locator("[data-quick-admin-rows] input").count()>0);
  await page.locator('[data-quick-time]').first().fill('08:45');
  await page.locator('[data-quick-title]').first().fill('Synthetic updated schedule');
  await page.locator('[data-quick-note]').first().fill('Synthetic short note');
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('dialog',{name:'Quick edit today',exact:true}).waitFor({state:'hidden'});
  assert.ok([...stored.values()].some(value=>value.includes('Synthetic updated schedule') && value.includes('08:45') && value.includes('Synthetic short note')),'Today times, titles and notes persist');
  await page.evaluate(()=>lockMobileAdmin());
  await page.waitForFunction(()=>!ADMIN_MODE && document.getElementById('app').textContent.length>500);
  assert.equal(role,null,'Lock removes server privilege and reloads public page');
  apiUnavailable=true;
  await page.reload();
  await page.getByRole('button',{name:'Complete Form',exact:true}).first().waitFor();
  assert.equal(await page.locator('input[type=password]').count(),0,'Unavailable server configuration does not block public tour');
  assert.equal(await page.evaluate(()=>USE_REMOTE_STORAGE),false,'Unavailable API disables remote writes');
  assert.deepEqual(errors,[],'No browser runtime errors');
  console.log('PASS: password-free root startup, admin password failure/unlock/lock, public startup with unavailable API, real Chrome mobile/desktop layout, Eurostar conditional fields and submission, shared Today/Itinerary resources, recap opening, no runtime errors. All requests mocked.');
} finally { await browser.close(); }
